name: Nightly Maintenance (related, topics, bibliography)
on:
  schedule:
    - cron: "15 3 * * *" # 03:15 UTC daily (tweak as you like)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: true }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: node scripts/build-related.js
      - run: node scripts/build-topic-indexes.js
      - run: node scripts/build-master-bibliography.js
      - name: Commit changes (if any)
        run: |
          git config user.name "automation-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "chore(automation): refresh related/topics/bibliography"
            git push
          fi
