name: Daily Article Discovery

on:
  schedule:
    # 15:00 UTC == 11:00 AM America/New_York during DST
    - cron: '0 15 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: daily-discovery
  cancel-in-progress: true

jobs:
  discover:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # NOTE: removed "cache: npm" because there is no lockfile

      - name: Run discovery
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SEARCH_ENGINE_ID: ${{ secrets.SEARCH_ENGINE_ID }}
        run: node src/discovery.js

      - name: Commit & push (only if changed)
        run: |
          git config user.name "automation"
          git config user.email "actions@users.noreply.github.com"
          git add data/
          git diff --staged --quiet || { git commit -m "chore(discovery): $(date -u +'%Y-%m-%d')"; git push; }

      # Prepare email subject from data/email-summary.json (falls back to "Nothing new")
      - name: Prepare email subject
        run: |
          SUBJECT="SOV-ARCH · $(date -u +%F) · Nothing new"
          if [ -f data/email-summary.json ]; then
            SUBJECT="$(node -e "const f='data/email-summary.json',fs=require('fs');let s='${SUBJECT}';if(fs.existsSync(f)){try{s=JSON.parse(fs.readFileSync(f,'utf8')).subject||s;}catch{}};console.log(s)")"
          fi
          echo "EMAIL_SUBJECT=$SUBJECT" >> $GITHUB_ENV

      # Load plain-text body from data/notification.txt (guaranteed by discovery.js)
      - name: Load email body (plain text)
        run: |
          echo 'EMAIL_BODY<<EOF' >> $GITHUB_ENV
          if [ -f data/notification.txt ]; then
            cat data/notification.txt >> $GITHUB_ENV
          else
            echo "Sovereignty System Report — $(date -u +%F)

Nothing new today." >> $GITHUB_ENV
          fi
          echo 'EOF' >> $GITHUB_ENV

      - name: Send email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}          # e.g. lehewych123@gmail.com
          password: ${{ secrets.SMTP_PASSWORD }}          # 16-char Gmail app password
          subject: ${{ env.EMAIL_SUBJECT }}
          to: lehewych123@gmail.com, daniel.lehewych.writer@gmail.com, dlehewych@gradcenter.cuny.edu
          from: "Sovereignty Bot <${{ secrets.SMTP_USERNAME }}>"
          content_type: text/plain; charset="utf-8"
          body: ${{ env.EMAIL_BODY }}
          attachments: |
            data/notification.html
            data/notification.txt
            data/notification.md
            data/new-articles-full.json
