name: Daily Article Discovery

on:
  workflow_dispatch:
  schedule:
    # 15:00 UTC == 11:00 AM America/New_York during DST
    - cron: '0 15 * * *'

permissions:
  contents: write

concurrency:
  group: daily-discovery
  cancel-in-progress: true

jobs:
  discover:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run discovery
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SEARCH_ENGINE_ID: ${{ secrets.SEARCH_ENGINE_ID }}
        run: node src/discovery.js

      - name: Commit & push (only if changed)
        run: |
          git config user.name "automation"
          git config user.email "actions@users.noreply.github.com"
          git add data/
          git diff --staged --quiet || { git commit -m "chore(discovery): $(date -u +'%Y-%m-%d')"; git push; }

      # Build a clean markdown email from notification.md (or a fallback)
      - name: Compose rich email body
        if: always()
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const p = 'data/notification.md';
          let body = `# Sovereignty System Report - ${new Date().toISOString().slice(0,10)}\n\n`;
          if (fs.existsSync(p) && fs.statSync(p).size > 0) {
            const md = fs.readFileSync(p, 'utf8');
            // strip a duplicate top header if present
            body += md.replace(/^#\s+Sovereignty.*\n*/i, '');
          } else {
            body += 'Nothing new today.';
          }
          fs.mkdirSync('data', {recursive:true});
          fs.writeFileSync('data/email.md', body);
          console.log('Wrote data/email.md');
          NODE

      # Send the email via Gmail SMTP (reads the file we just created)
      - name: Email report
        if: always()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}          # your Gmail address
          password: ${{ secrets.SMTP_PASSWORD }}          # the 16-char app password
          from: Daniel Lehewych <${{ secrets.SMTP_USERNAME }}>
          to: lehewych123@gmail.com, daniel.lehewych.writer@gmail.com, dlehewych@gradcenter.cuny.edu
          subject: Sovereignty Report – ${{ github.repository }} run #${{ github.run_number }}
          content_type: text/markdown
          convert_markdown: true
          body: file://data/email.md
          attachments: |
            data/new-articles-full.json
            data/notification.md
