name: Daily Article Discovery

on:
  workflow_dispatch:
  schedule:
    # 15:00 UTC == 11:00 AM America/New_York during DST
    - cron: '0 15 * * *'

permissions:
  contents: write

concurrency:
  group: daily-discovery
  cancel-in-progress: true

jobs:
  discover:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run discovery
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SEARCH_ENGINE_ID: ${{ secrets.SEARCH_ENGINE_ID }}
          DISCOVERY_LANG: en
        run: node src/discovery.js

      - name: Commit & push (only if changed)
        run: |
          git config user.name "automation"
          git config user.email "actions@users.noreply.github.com"
          git add data/
          git diff --staged --quiet || { git commit -m "chore(discovery): $(date -u +'%Y-%m-%d')"; git push; }

      - name: Read notification for email
        id: note
        if: always()
        run: |
          if [ -s data/notification.md ]; then
            echo 'body<<EOF' >> $GITHUB_OUTPUT
            cat data/notification.md >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT
          else
            echo 'body<<EOF' >> $GITHUB_OUTPUT
            echo "# Sovereignty System Report - $(date -u +%F)\n\nNothing new today." >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT
          fi

      - name: Email report
        if: always()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}          # your Gmail address
          password: ${{ secrets.SMTP_PASSWORD }}          # 16-char app password
          from: Daniel Lehewych <${{ secrets.SMTP_USERNAME }}>
          to: lehewych123@gmail.com, daniel.lehewych.writer@gmail.com, dlehewych@gradcenter.cuny.edu
          subject: Sovereignty Report – ${{ github.repository }} run #${{ github.run_number }}
          convert_markdown: true
          body: ${{ steps.note.outputs.body }}
          attachments: |
            data/new-articles-full.json
            data/notification.md
