name: Outbox Shipper
on:
  schedule:
    - cron: "20 13 * * *"   # adjust timing
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Optional: if you want to smoke-test shipping manually in this same run,
      # uncomment the next 3 lines to generate outbox here.
      # - uses: actions/setup-node@v4
      #   with: { node-version: '20' }
      # - run: node scripts/smoke-generate-outbox.js

      - name: Check for outbox payload
        id: scan
        shell: bash
        run: |
          shopt -s globstar nullglob
          files=(data/outbox/**)
          if (( ${#files[@]} > 0 )); then
            echo "present=true" >> "$GITHUB_OUTPUT"
            echo "count=${#files[@]}" >> "$GITHUB_OUTPUT"
          else
            echo "present=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Nothing to ship; exit cleanly
        if: steps.scan.outputs.present == 'false'
        run: echo "No outbox found (no new/updated items). Skipping." && exit 0

      - name: Send email with outbox
        if: steps.scan.outputs.present == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          secure: true
          from: Daniel Lehewych <${{ secrets.SMTP_USERNAME }}>
          to: ${{ secrets.EMAIL_TO }}
          subject: "SOV-ARCH Outbox · ${{ github.repository }} · Run #${{ github.run_number }}"
          convert_markdown: true
          html_body: file://data/notification.md
          attachments: |
            data/outbox/**/header.html
            data/outbox/**/page.html
            data/outbox/**/schema.json
            data/outbox/**/topic.json
            data/outbox/**/related.json
            data/outbox/**/bib.json
            data/outbox/**/meta.json
